<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>50d85316-0737-4fd9-bfbf-481d813e089e</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Markdig" Version="1.4.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.4">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Enrichers.Environment" Version="3.0.1" />
    <PackageReference Include="Serilog.Enrichers.Thread" Version="4.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FlowIQ.Application\FlowIQ.Application.csproj" />
    <ProjectReference Include="..\FlowIQ.Infrastructure\FlowIQ.Infrastructure.csproj" />
    <ProjectReference Include="..\FlowIQ.Contracts\FlowIQ.Contracts.csproj" />
    <ProjectReference Include="..\FlowIQ.Domain\FlowIQ.Domain.csproj" />
  </ItemGroup>

</Project>
